stages:
  clean_models:
    cmd: python -c "import shutil, os; shutil.rmtree('models', ignore_errors=True); os.makedirs('models', exist_ok=True)"
    always_changed: true

  prepare_data_text:
    cmd: python scripts/prepare_data.py
    deps:
      - scripts/prepare_data.py
    outs:
      - data/dataset.csv


  train_text_baseline:
    cmd: python scripts/train_text_baseline.py
    deps:
      - data/dataset.csv
      - scripts/train_text_baseline.py
    outs:
      - models/text_baseline_model.pkl
      - models/text_baseline_vectorizer.pkl


  train_text_mlflow:
    cmd: python scripts/train_mlflow.py
    deps:
      - data/dataset.csv
      - scripts/train_mlflow.py
    outs:
      - models/text_mlflow_model.pkl
      - models/text_mlflow_vectorizer.pkl


  train_text_wandb:
    cmd: python scripts/train_logistic_wandb.py
    deps:
      - data/dataset.csv
      - scripts/train_logistic_wandb.py
    outs:
      - models/text_wandb_model.pkl
      - models/text_wandb_vectorizer.pkl

  predict_text_any:
    cmd: python scripts/predict_text_any.py --input data/predict_texts.txt --out predictions/text_any_output.csv --meta predictions/text_any_meta.json
    deps:
      - scripts/predict_text_any.py
      - models/       
    outs:
      - predictions/text_any_output.csv
    metrics:
      - predictions/text_any_meta.json

  prepare_cifar10:
    cmd: python scripts/prepare_cifar10.py
    deps:
      - scripts/prepare_cifar10.py
    outs:
      - data/cifar10/train.npz:
          cache: false
      - data/cifar10/test.npz:
          cache: false

  # تدريب الصور - بدون أداة تتبّع (Baseline)
  train_cifar10_baseline:
    cmd: python scripts/train_cifar10.py
    deps:
      - data/cifar10/train.npz
      - data/cifar10/test.npz
      - scripts/train_cifar10.py
    outs:
      - models/cifar10_model_baseline.keras

 
  train_cifar10_mlflow:
    cmd: python scripts/train_cifar10_mlflow.py
    deps:
      - data/cifar10/train.npz
      - data/cifar10/test.npz
      - scripts/train_cifar10_mlflow.py
    outs:
      - models/cifar10_model_mlflow.keras

  train_cifar10_wandb:
    cmd: python scripts/train_cifar10_wandb.py
    deps:
      - data/cifar10/train.npz
      - data/cifar10/test.npz
      - scripts/train_cifar10_wandb.py
    outs:
      - models/cifar10_model_wandb.keras
      
  predict_cifar10_any:
    cmd: python scripts/predict_cifar10_any.py --in data/cifar10/test.npz --out predictions/cifar10_any_preds.npy --meta predictions/cifar10_any_meta.json --sample 0
    deps:
      - scripts/predict_cifar10_any.py
      - data/cifar10/test.npz
      - models/
    outs:
      - predictions/cifar10_any_preds.npy
    metrics:
      - predictions/cifar10_any_meta.json
